# Generated by Django 4.1.7 on 2023-04-07 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 6, 41, 0, 830340, tzinfo=datetime.timezone.utc)),
        ),
    ]
